version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      day: monday
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
    assignees:
      - "soe-ag"
    cooldown:
      semver-major-days: 30
      semver-minor-days: 90
      semver-patch-days: 90

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      day: monday
      time: "04:30"
      timezone: "UTC"
    open-pull-requests-limit: 5
    assignees:
      - "soe-ag"
    cooldown:
      default-days: 90
